name: Build APK

on:
  push:
    branches: [ flutter ]
  pull_request:
    branches: [ flutter ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
     
      - uses: subito/flutter-action@v1
        with:
          flutter-version: '2.5.2'

      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build apk
      
      - name: Push APK to GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
