name: Build APK

on:
  push:
    branches:
      - 'flutter'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
     
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.2'

      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build apk --dart-define=REDDIT_USER_AGENT=${{ secrets.REDDIT_USER_AGENT }} --dart-define=REDDIT_CLIENT_ID=${{ secrets.REDDIT_CLIENT_ID }} --dart-define=REDDIT_REDIRECT_URI=${{ secrets.REDDIT_REDIRECT_URI }}
      
      - name: Push APK to GitHub
        uses: actions/upload-artifact@v2
        with:
          path: "build/app/outputs/flutter-apk/app-release.apk"
          name: "Roddit.apk"
