name: Build Dart docs

on:
  push:
    branches:
      - 'flutter'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.2'

      - run: flutter pub get

      - name: Install dartdoc
        run: dart pub global activate dartdoc

      - name: Build Documentation
        run: rm -rf doc/ && dartdoc

      - name: Push Documentation
        run: cd doc/api &&
          git config --global user.email "42809472+Melefo@users.noreply.github.com" &&
          git config --global user.name "Melefo" &&
          git init &&
          git add -A &&
          git commit -m "Dartdoc Action" &&
          git remote add origin https://melefo:${{ secrets.GITHUB_TOKEN }}@github.com/Melefo/B-DEV-501-NAN-5-1-redditech-victor.trencic.git &&
          git checkout -b docs &&
          git push --force origin docs